### ISSUE TITLE
failed to compile

### ISSUE THREAD

**Issue by nissimzur** [jhuggard-ucd/ESP32_IoT_Device_First_Boot#1]
Hi
It failed to compile with this error. I am running ESP-IDF v4.2-dev-1905-g625bd5eb1-dirty
Any suggestion? 
Thank you.

[10/163] Linking CXX static library esp-idf\freemodbus\libfreemodbus.a
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

**Comment by jhuggard-ucd** [comment]
Hi
Can you check in your project folder: "build\esp-idf\freemodbus\libfreemodbus.a" exists?

If this is not the issue, I have made a new commit just now which I have successfully run on that version. Hope this helps.

**Comment by nissimzur** [comment]
All work now OK. 
Great work. 
Thank you. 
-Nissim
