### ISSUE TITLE
failed to connect to AP after capative setting

### ISSUE THREAD

**Issue by nissimzur** [jhuggard-ucd/ESP32_IoT_Device_First_Boot#2]
Hi
It seems some bug prevents the code from open STA and connects to home AP after phone capative setting. 
The AP scan and show all AP around on the Android phone  - 100% OK.
After selecting one AP.
The AP name appears bad, as nonascii character, and just 4 characters. 
Entering the password did not make it connect. 
It stays in an endless loop. 
running ESP_ERROR_CHECK(nvs_flash_erase()); did not change anything. 
see http://calllan.com/bad_AP_name.PNG
The AP name was nissim-hot
Thank you 
-Nissim

**Comment by jhuggard-ucd** [comment]
Hi,
I have addressed the bad AP name issue in the latest update. You may need to use "idf.py erase_flash" to ensure that there are no persistent issues from memory written in the last version if it does not work straight away.

**Comment by nissimzur** [comment]
Hi
I did erase_flash
![bad_AP_name](https://user-images.githubusercontent.com/3673671/87144454-71f2ed80-c2b0-11ea-9ef9-6aa167f8d61f.PNG)
. 
This is my batch file:

rem idf.py -p COM18 erase_flash -b 921600 
idf.py fullclean
idf.py menuconfig
idf.py -p COM18 flash -b 921600 monitor
 

The same bad SSID name shows on the phone. (same as I send yesterday)
Just 3 nonascii and the 4 is "?"
The said I select from the list button was nissim-hot

during build I got this:
esptool.py v3.0-dev
Generated V:/ESP-IDF/esp32/esp-idf/examples/wifi/nissim3/captive_portal/Captive_Portal_1/build/bootloader/bootloader.bin
[947/956] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/example_secondary_app.c.obj
In file included from ../main/thingspeak.h:22,
                 from ../main/example_secondary_app.h:36,
                 from ../main/example_secondary_app.c:14:
../main/http.h:38: warning: "ESP_ERR_HTTP_BASE" redefined
 #define ESP_ERR_HTTP_BASE 0x40000

In file included from ../main/example_secondary_app.h:28,
                 from ../main/example_secondary_app.c:14:
../../../../../../components/esp_http_client/include/esp_http_client.h:140: note: this is the location of the previous definition
 #define ESP_ERR_HTTP_BASE               (0x7000)                    /*!< Starting number of HTTP error codes */

../main/example_secondary_app.c: In function 'log_to_thingspeak':
../main/example_secondary_app.c:27:22: warning: variable 'val_type' set but not used [-Wunused-but-set-variable]
  esp_adc_cal_value_t val_type;
                      ^~~~~~~~
[949/956] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/iot_fb_main.c.obj
In file included from ../main/thingspeak.h:22,
                 from ../main/iot_fb_main.c:40:
../main/http.h:38: warning: "ESP_ERR_HTTP_BASE" redefined
 #define ESP_ERR_HTTP_BASE 0x40000

In file included from ../main/iot_fb_main.c:31:
../../../../../../components/esp_http_client/include/esp_http_client.h:140: note: this is the location of the previous definition
 #define ESP_ERR_HTTP_BASE               (0x7000)                    /*!< Starting number of HTTP error codes */

[955/956] Generating binary image from built executable
esptool.py v3.0-dev
Generated V:/ESP-IDF/esp32/esp-idf/examples/wifi/nissim3/captive_portal/Captive_Portal_1/build/softAP.bin




Thank you for your help.
-Nissim

**Comment by jhuggard-ucd** [comment]
Hi Nissim,
Can you confirm that you are using the most recent commit? Line 81 in file iot_fb_main.c should read:
			init_memory(FIRST_BOOT_NAMESPACE);
This was part of a fix for that bad AP issue. If this does not work, can you send on the terminal output from the ESP32 from boot to this issue occurring?

**Comment by nissimzur** [comment]
Yes, init_memory(FIRST_BOOT_NAMESPACE); shows at line 81
I notice that the place of the project directory has some wired effects on IDE, when path greater than 256 characters. 
So I download your project again from github  to v:\work\ESP32_IoT_Device_First_Boot-master  and clear ESP32 flash, build and flash again. 
Now it shows my home AP good. no wired characters gets the SSID password and links to home AP great as STA. 
But to see the Captive screen, I need to search for some web page on my phone after link to ESP32 captive AP. 
It does not show a captive web page without doing that search. 
Is that the way it supposes to work? 
In Airport the welcome captive web page normally shows immediately after selecting the Airport AP. Without looking for any web page on the internet. 
How does the project act on your side? when you select the captive AP and key in the password, do you see immediately the list of AP around and the name of your home AP you like to connect? Key in the password and its works?


Thank you for your support. 
-Nissim Zur

**Comment by jhuggard-ucd** [comment]
Hi Nissim, 
Glad to hear that resolved the bad AP issue. The captive portal at the moment acts exactly as you have described it. It will only pick up on simple DNS queries (specifically single-query ipv4 internet address requests) from a device making a request, usually initiated by the user. In order for it to act as airport hotspots do, as you described, will take some more development of the DNS message types handled in captive_portal.c. Hopefully these will be incorporated in coming weeks.

**Comment by nissimzur** [comment]
Thank you.
I notice that Android sends DNS requests and pings to some web site when connected to any new AP.
 I believe it to find if the new AP has an active internet connection. 
Do, you like me to intercept this request and send the inner web page as trying to imitate the captive web effect in Airports? 
I do no know how to work with Git. So I can send you all findings and code change to integrate into your source. If you like. 
Best regrades,
My whatsup is Nissim Zur +972544500635, You are welcome to connect. 
-Nissim

**Comment by jhuggard-ucd** [comment]
It seems you are correct that there are specific DNS requests made to websites on connection. The latest commit deals with opening a web browser on connection from a user device to the ESP32. I have gotten it to work reliably on iOS. Would be interested to hear if it is successful on Android.

**Comment by nissimzur** [comment]
If you have a code update to open web on iOS connection, please share it with me. I am still learning your older code. 
I will add the Android version call to it and send you back. 
My whatsup is +972544500635 nissim.zur@gmail.com
Thank you
Nissim

**Comment by nissimzur** [comment]
with new updates, it works also with android. 
Greetings.
-Nissim
