### ISSUE TITLE
If the use enter a bad AP password, he can't fix it without the clear NVS button. 

### ISSUE THREAD

**Issue by nissimzur** [jhuggard-ucd/ESP32_IoT_Device_First_Boot#3]
now captive work as in Airport. Great. Very nice code. I believe you are the first to solve that problem so nicely.
one minor issue:
If the user key into selected AP  the password.  The code enters to endless loops, trying to connect to selected AP with bad passwords. 
The only way to clear that is to clear NVS with a button. 
The button is not always passable. for example in some water shield devices. Or devices place in high places. 

Maybe connection_check.html is shown and removed from the phone screen to fast. 
If it will show some progress and have a button to go back to network_select.html it can solve the problem.

**Comment by jhuggard-ucd** [comment]
This has been addressed in the most recent update to the code. If the wrong password is entered, the connection check page will inform user and give button to redirect to network_select.html. This fix may be readdressed in future but gives consistent performance for now.
