### ISSUE TITLE
Endless loop stay in code from yesterday. (21H back)

### ISSUE THREAD

**Issue by nissimzur** [jhuggard-ucd/ESP32_IoT_Device_First_Boot#4]
it seems that the last change you make shows endless loop the web page **connection_check.html**
The log shows endless loop also I (212841) is_sta_connected: 0
I believe if the home AP password is wrong I (212841) is_sta_connected: 0 it has to send the network_select.html to the user phone to fix it. 
Maybe after 5 "**is_sta_connected: 0**" retries and with no NVS erased. (Maybe AP is temporary down, so next ESP reset it can be connected.

**Comment by jhuggard-ucd** [comment]
This has been addressed by removing the loop from the code. Instead now a single request is made and the ESP32 responds to that request on connection or failure to connect.
